export const AUTHSTATE = "USER/AUTHSTATE"

export const SIGNUP = "USER/SIGNUP"
export const SIGNIN = "USER/SIGNIN"

export const UPDATEPROFILE = "USER/UPDATEPROFILE"
export const DOWNLOADPROFILE = "USER/DOWNLOADPROFILE"